services:
  liliana:
    image: liliana:latest
    build:
      context: .
      target: devimage
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://liliana:liliana@postgres:5432/liliana_test?sslmode=disable
      LILIANA_POSTGRES_TEST_DSN: postgres://liliana:liliana@postgres:5432/liliana_test?sslmode=disable

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: liliana
      POSTGRES_PASSWORD: liliana
      POSTGRES_DB: liliana_test
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liliana -d liliana_test"]
      interval: 5s
      timeout: 5s
      retries: 5
